### ISSUE TITLE
1.21.3 renamed #hurt -> #hurtServer

### ISSUE THREAD

**Issue by lolo45654** [mcpvp-club/FasterCrystals#31]
`boolean hurtServer(ServerLevel world, DamageSource source, float amount)`

the Entity class has a compatibility method but that doesn't work. maybe because it doesnt return a boolean unlike what the compiler compiles.

```
[10:15:15 WARN]: [FasterCrystals] Task #581 for FasterCrystals v1.9.0 generated an exception
java.lang.NoSuchMethodError: 'boolean net.minecraft.world.entity.boss.enderdragon.EndCrystal.hurt(net.minecraft.world.damagesource.DamageSource, float)'
        at pvpclub-FasterCrystals-1.9.0.jar/xyz.reknown.fastercrystals.listeners.packet.AnimationListener.lambda$onPacketPlayReceive$1(AnimationListener.java:113) ~[pvpclub-FasterCrystals-1.9.0.jar:?]
        at pvpclub-FasterCrystals-1.9.0.jar/xyz.reknown.fastercrystals.packetevents.impl.util.folia.EntityScheduler.lambda$run$0(EntityScheduler.java:80) ~[pvpclub-FasterCrystals-1.9.0.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.3.jar:1.21.3-58-bf8405f]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474) ~[paper-1.21.3.jar:1.21.3-58-bf8405f]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1803) ~[paper-1.21.3.jar:1.21.3-58-bf8405f]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1664) ~[paper-1.21.3.jar:1.21.3-58-bf8405f]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1329) ~[paper-1.21.3.jar:1.21.3-58-bf8405f]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-58-bf8405f]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Jyguy** [comment]
Not sure how this went through my testing. Thanks for the report!
