### ISSUE TITLE
Error cannot run on 1.21.1 Folia

### ISSUE THREAD

**Issue by tuannz2911** [mcpvp-club/FasterCrystals#32]
`[04:43:02] [Server thread/INFO]: [FasterCrystals] Enabling FasterCrystals v1.9.1
[04:43:02] [Server thread/ERROR]: Error occurred while enabling FasterCrystals v1.9.1 (Is it up to date?)
java.lang.IllegalStateException: Tried to access CommandAPIHandler instance, but it was null! Are you using CommandAPI features before calling CommandAPI#onLoad?
	at pvpclub-FasterCrystals-1.9.1.jar/xyz.reknown.fastercrystals.commandapi.CommandAPIHandler.getInstance(CommandAPIHandler.java:172) ~[pvpclub-FasterCrystals-1.9.1.jar:?]
	at pvpclub-FasterCrystals-1.9.1.jar/xyz.reknown.fastercrystals.commandapi.CommandAPI.onEnable(CommandAPI.java:154) ~[pvpclub-FasterCrystals-1.9.1.jar:?]
	at pvpclub-FasterCrystals-1.9.1.jar/xyz.reknown.fastercrystals.FasterCrystals.onEnable(FasterCrystals.java:73) ~[pvpclub-FasterCrystals-1.9.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[foldenor-1.21.1.jar:1.21.1-DEV-aa661cb]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[foldenor-1.21.1.jar:1.21.1-DEV-aa661cb]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:657) ~[?:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:606) ~[?:?]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:776) ~[foldenor-1.21.1.jar:1.21.1-DEV-aa661cb]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:523) ~[foldenor-1.21.1.jar:1.21.1-DEV-aa661cb]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:336) ~[foldenor-1.21.1.jar:1.21.1-DEV-aa661cb]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1276) ~[foldenor-1.21.1.jar:1.21.1-DEV-aa661cb]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:353) ~[foldenor-1.21.1.jar:1.21.1-DEV-aa661cb]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[04:43:02] [Server thread/INFO]: [FasterCrystals] Disabling FasterCrystals v1.9.1`

**Comment by Jyguy** [comment]
I'm unable to reproduce this on Folia `1.21.1-DEV-dev/1.21.1@2e7bc07`. It is likely an incompatibility with the fork; note that FasterCrystals only supports compatible forks of Paper and Folia.

If you're able to reproduce this on base Folia let me know.
