### ISSUE TITLE
SPAM ERROR in 1.21.3

### ISSUE THREAD

**Issue by Darkmager** [mcpvp-club/FasterCrystals#34]
java.lang.UnsupportedOperationException: Unsupported custom data nbt type: NBTByte
        at pvpclub-FasterCrystals-1.9.1 (1).jar/xyz.reknown.fastercrystals.packetevents.api.protocol.component.builtin.item.CustomData.read(CustomData.java:39) ~[pvpclub-FasterCrystals-1.9.1 (1).jar:?]
        at pvpclub-FasterCrystals-1.9.1 (1).jar/xyz.reknown.fastercrystals.packetevents.api.protocol.component.StaticComponentType.read(StaticComponentType.java:69) ~[pvpclub-FasterCrystals-1.9.1 (1).jar:?]
        at pvpclub-FasterCrystals-1.9.1 (1).jar/xyz.reknown.fastercrystals.packetevents.api.wrapper.PacketWrapper.readItemStackModern(PacketWrapper.java:483) ~[pvpclub-FasterCrystals-1.9.1 (1).jar:?]
        at pvpclub-FasterCrystals-1.9.1 (1).jar/xyz.reknown.fastercrystals.packetevents.api.wrapper.PacketWrapper.readItemStack(PacketWrapper.java:502) ~[pvpclub-FasterCrystals-1.9.1 (1).jar:?]
        at pvpclub-FasterCrystals-1.9.1 (1).jar/xyz.reknown.fastercrystals.packetevents.api.wrapper.PacketWrapper.readMap(PacketWrapper.java:434) ~[pvpclub-FasterCrystals-1.9.1 (1).jar:?]
        at pvpclub-FasterCrystals-1.9.1 (1).jar/xyz.reknown.fastercrystals.packetevents.api.wrapper.play.client.WrapperPlayClientClickWindow.read(WrapperPlayClientClickWindow.java:77) ~[pvpclub-FasterCrystals-1.9.1 (1).jar:?]
        at pvpclub-FasterCrystals-1.9.1 (1).jar/xyz.reknown.fastercrystals.packetevents.api.wrapper.PacketWrapper.readEvent(PacketWrapper.java:277) ~[pvpclub-FasterCrystals-1.9.1 (1).jar:?]
        at pvpclub-FasterCrystals-1.9.1 (1).jar/xyz.reknown.fastercrystals.packetevents.api.wrapper.PacketWrapper.<init>(PacketWrapper.java:167) ~[pvpclub-FasterCrystals-1.9.1 (1).jar:?]
        at pvpclub-FasterCrystals-1.9.1 (1).jar/xyz.reknown.fastercrystals.packetevents.api.wrapper.PacketWrapper.<init>(PacketWrapper.java:157) ~[pvpclub-FasterCrystals-1.9.1 (1).jar:?]
        at pvpclub-FasterCrystals-1.9.1 (1).jar/xyz.reknown.fastercrystals.packetevents.api.wrapper.play.client.WrapperPlayClientClickWindow.<init>(WrapperPlayClientClickWindow.java:42) ~[pvpclub-FasterCrystals-1.9.1 (1).jar:?]
        at pvpclub-FasterCrystals-1.9.1 (1).jar/xyz.reknown.fastercrystals.listeners.packet.LastPacketListener.getAnimPacket(LastPacketListener.java:75) ~[pvpclub-FasterCrystals-1.9.1 (1).jar:?]
        at pvpclub-FasterCrystals-1.9.1 (1).jar/xyz.reknown.fastercrystals.listeners.packet.LastPacketListener.onPacketPlayReceive(LastPacketListener.java:49) ~[pvpclub-FasterCrystals-1.9.1 (1).jar:?]
        at pvpclub-FasterCrystals-1.9.1 (1).jar/xyz.reknown.fastercrystals.packetevents.api.event.SimplePacketListenerAbstract.onPacketReceive(SimplePacketListenerAbstract.java:49) ~[pvpclub-FasterCrystals-1.9.1 (1).jar:?]
        at pvpclub-FasterCrystals-1.9.1 (1).jar/xyz.reknown.fastercrystals.packetevents.api.event.PacketReceiveEvent.call(PacketReceiveEvent.java:44) ~[pvpclub-FasterCrystals-1.9.1 (1).jar:?]
        at pvpclub-FasterCrystals-1.9.1 (1).jar/xyz.reknown.fastercrystals.packetevents.api.event.EventManager.callEvent(EventManager.java:84) ~[pvpclub-FasterCrystals-1.9.1 (1).jar:?]
        at pvpclub-FasterCrystals-1.9.1 (1).jar/xyz.reknown.fastercrystals.packetevents.api.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:101) ~[pvpclub-FasterCrystals-1.9.1 (1).jar:?]
        at pvpclub-FasterCrystals-1.9.1 (1).jar/xyz.reknown.fastercrystals.packetevents.impl.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:57) ~[pvpclub-FasterCrystals-1.9.1 (1).jar:?]
        at pvpclub-FasterCrystals-1.9.1 (1).jar/xyz.reknown.fastercrystals.packetevents.impl.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:64) ~[pvpclub-FasterCrystals-1.9.1 (1).jar:?]
        at pvpclub-FasterCrystals-1.9.1 (1).jar/xyz.reknown.fastercrystals.packetevents.impl.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:41) ~[pvpclub-FasterCrystals-1.9.1 (1).jar:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.InboundProtocolReader.channelRead(InboundProtocolReader.java:25) ~[ProtocolLib.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202) ~[netty-handler-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164) ~[netty-handler-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[netty-handler-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Jyguy** [comment]
Can you try using https://github.com/mcpvp-club/FasterCrystals/actions/runs/12279209358? This is a packetevents issue and it was probably fixed when it was updated.

**Comment by Jyguy** [comment]
Assumed to have been fixed by PE update.
